### ISSUE TITLE
The menu on Linux dark theme is just hard to read

### ISSUE THREAD

**Issue by Getron** [simlu/voxelshop#3] opened 2016-06-26 21:22 UTC
Hi

On my dark-themed Linux distro, Netrunner 16.01 KDE Arch rolling release, the menu is just hard to read, because, it is white.

It should take, or listen to the system themes of OS.
![voxelshop](https://cloud.githubusercontent.com/assets/5913218/16365022/e8ca3f4a-3bf4-11e6-9def-abfea0d8caaa.jpeg)

**Comment by simlu** [comment] 2016-07-01 17:29
Ah yes, that's a longer term known issue. The problem is that it's currently very hard for me to debug and I'm using a very old JIDE version (from four years ago). Will try to look into this soon!

**Comment by simlu** [comment] 2016-07-01 19:16
Fixed in Version >= 1.5.07

**Closed by simlu** 2016-07-01 19:16 UTC
