### ISSUE TITLE
Moving mini sized window on Linux cause the automatic maximizing the window

### ISSUE THREAD

**Issue by Getron** [simlu/voxelshop#2] opened 2016-06-26 21:11 UTC
Hi

I just try the new Voxeshop, and if i resize the window, and moving it around, on mouse release, it maximize to the full screen window, which it should not do.

My OS is Netrunner 16.01 KDE Arch rolling release, with dark theme.

Please fix this isue.

**Comment by simlu** [comment] 2016-07-01 17:34
Interesting. It should do that on double click, but not on release. Possibly picking up a weird double click speed somewhere?

The problem is in
```java
public void mouseReleased(MouseEvent e) {
    // change maximized state on dbl click
    if (e.getClickCount()%2 == 0) {
        setMaximized(frame, !isMaximized(frame));
    }
}
```
Somehow the click count is screwed up. I can solve this with a timeout, which should fix your issue.

**Comment by simlu** [comment] 2016-07-01 18:02
Can you please confirm that this is fixed in Versions >= 1.5.04
Thank you

**Comment by simlu** [comment] 2016-10-22 03:41
@Getron Can you please confirm?

**Comment by simlu** [comment] 2016-11-27 18:29
@funabab Can you confirm this is fixed? Thanks

**Comment by funabab** [comment] 2016-11-28 00:07
No such issue here on linux ubuntu 16.04 LTS, so we can agree that this is fixed

**Closed** 2016-11-28 00:08 UTC
Labels: bug
